#!/bin/bash
set -e

THIRDPARTY_DIR="$(pwd)/thirdparty"
mkdir -p "$THIRDPARTY_DIR"

echo "====================================================="
echo " Setting up Foundation Models for Benchmarking "
echo "====================================================="
echo ""
echo "OrthoTrack's foundation model benchmark utilizes MapAnything as a unified wrapper"
echo "to load models like DUSt3R, MASt3R, MoGe, VGGT, Pi3, and DA3."
echo ""
echo "Please obtain access to the following repositories and clone them into $THIRDPARTY_DIR:"
echo ""
echo "1. MapAnything (Meta Research):"
echo "   git clone https://github.com/facebookresearch/map-anything.git $THIRDPARTY_DIR/mapanything"
echo "   cd $THIRDPARTY_DIR/mapanything && pip install -e ."
echo ""
echo "2. Depth Anything 3 (DA3):"
echo "   git clone https://github.com/ByteDance-Seed/Depth-Anything-3.git $THIRDPARTY_DIR/thirdparty_da3"
echo "   cd $THIRDPARTY_DIR/thirdparty_da3 && pip install -e ."
echo ""
echo "3. Pi3 / Pi3X (yyfz):"
echo "   git clone https://github.com/yyfz/Pi3.git $THIRDPARTY_DIR/thirdparty_pi3"
echo "   cd $THIRDPARTY_DIR/thirdparty_pi3 && pip install -e ."
echo ""
echo "Other models like MoGe and DUSt3R will automatically download their weights from"
echo "HuggingFace at runtime when requested."
echo ""
echo "This is OPTIONAL evaluation tooling — not required for OrthoTrack tracking."
echo "After cloning/installing the packages above into your env, re-run"
echo "scripts/run_foundation_models.py for the models you need."
echo "See EVALUATION.md for full notes."
